### ISSUE TITLE
Suggestion for sweet.hpp/comparetest/comparetest.cpp

### ISSUE THREAD

**Issue by timmi-on-rails** [burner/sweet.hpp#14]
Hello,
nice work there. 

I would use the compare.hpp also because I don't like that (-1 == 4294967295u).
sweet::equal works as expected.

I suggest you add something like this to your tests at `sweet.hpp/comparetest/comparetest.cpp` to document this usage scenario:
```
AS_F(sweet::equal(-1, 4294967295u));
AS_F(sweet::equal(4294967295u, -1));
```

**Comment by burner** [comment]
PRs are welcome

**Comment by timmi-on-rails** [comment]
#15
