### ISSUE TITLE
malloc hooks have been removed in glibc 2.34, `death.hpp` errors.

### ISSUE THREAD

**Issue by KOLANICH** [burner/sweet.hpp#18]
`man __malloc_hook`

>from glibc 2.34 onwards, all the hook variables have been removed from the API. Programmers should instead preempt calls to the relevant functions by defining and exporting malloc(), free(), realloc(), and calloc().

**Comment by burner** [comment]
I fear I can't really help with this. I haven't used this file for nearly 10 years at this point. But PR's are always welcome.

**Comment by KOLANICH** [comment]
Why is `malloc` within `backtrace` has to be worked around?

**Comment by burner** [comment]
because malloc might be the cause of the death

**Comment by KOLANICH** [comment]
https://man7.org/linux/man-pages/man3/backtrace.3.html

>backtrace() and backtrace_symbols_fd() don't call malloc() explicitly, but they are part of libgcc, which gets loaded dynamically when first used. Dynamic loading usually triggers a call to malloc(3). If you need certain calls to these two functions to not allocate memory (in signal handlers, for example), you need to make sure libgcc is loaded beforehand.
