### ISSUE TITLE
Specify License in README.md

### ISSUE THREAD

**Issue by t-moe** [burner/sweet.hpp#6]
Hey. Quite a big collection of headerfiles here:) 
We would like to use some of them in our products. Could you tell us which license applies?

**Comment by burner** [comment]
It is all LGPL. Hope that helps. May I ask what your are working on?

p.s. I will add a license line to those header having none.

**Comment by t-moe** [comment]
Thanks for clarifying. According to https://help.github.com/articles/open-source-licensing/ you should declare your license in the LICENSE.md file of the root folder or otherwise the default copyright applies. You fixed that with https://github.com/burner/sweet.hpp/commit/47a66e1c948f4c316dd0560d82b78d29a53d38dc .

We use some template magic to instantiate a lot of templates. Each template implements a "Operator" to compare arbitrary types. Some of the templates are guarded with an enable_if. Your compare.hpp provides a perfect solution for the interger-compare operators.

Thanks again.

**Comment by burner** [comment]
compare.hpp: Yeah I was fed up with g++ and clang basically telling me "Your are stupid" for every sign unsign comparison . I searched for a header similar to compare.hpp but couldn't find any, so I created it.

Anyway, thank you for taking an interest.
